[build]
  publish = "packages/app/frontend/blockscout-app"
  command = "cd packages/app/frontend/blockscout-app && npm install --force --legacy-peer-deps && npm run build"

[build.environment]
  PHP_VERSION = "8.1"
  NODE_VERSION = "18.18.0" 